#dev 开发环境

#tocmat设置
server:
  port: 9002
  tomcat:
    #  设置tomcat编码
    uri-encoding: UTF-8
    #设置信任的访问地址，允许哪个ip地址可以访问,支持正则
    #默认:“10\.\d{1,3}\.\d{1,3}\.\d{1,3}| 192\.168\.\d{1,3}\.\d{1,3}| 169\.254\.\d{1,3}\.\d{1,3}| 127\.\d{1,3}\.\d{1,3}\.\d{1,3}| 172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}| 172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}”
    #   internal-proxies:
    #tomcat的最大线程工作数
    max-threads: 50
  #    允许的http请求
  port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
#  指定服务器绑定的地址
#  address: 192.168.1.178
spring:
  #限制上传文件大小，springboot默认限制为2M
  http:
    multipart:
      enabled: true
      #      单个文件大小
      max-file-size: 50MB
      #      单次请求文件大小，为了应对多个文件同时上传的情况
      max-request-size: 50MB
  # class文件编码
  mandatory-file-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates
    encoding: UTF-8
  #?是否开启thymeleaf缓存，生产期建议false
  cache: false
  #email
  mail:
    host: smtp.163.com
    username: 用户163邮箱
    password: 邮箱密码
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

  #    datasource
  #log4j jdbc
  #  datasource:
  #    url: jdbc:log4jdbc:mysql://localhost/zl2?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #    username: root
  #    password: root
  #    driver-class-name: net.sf.log4jdbc.DriverSpy
  #    springboot jdbc
  datasource:
    url: jdbc:mysql://${blackup.databaseHost}/${blackup.databaseName}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #     控制台彩色输出
  output:
    ansi:
      enabled: ALWAYS
  #      应对OPTIONS请求，权限判断会出现此请求
  mvc:
    dispatch-options-request: true
    #    默认静态路径
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${file.fileUpPath}

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#默认分页条数
page:
  pageSize: 15

#banner 启动动画文件
# 启动动画文件编码
banner:
  charset: UTF-8
# 启动动画文件地址
#  location: classpath:banner.txt

#配置日志
logging:
  #  默认日志格式 10M自动分割 最多存在7个文件
  file: hbcrm.log
  level:
    com.hengbang.hbcrm: debug
#  采用xml 自定义日志格式，分割方式等
#  config: classpath:loggback.xml

file:
  #文件上传地址
  fileUpPath: ${windowsfile}/img/
  #  文件上传后缀限制
  fileSuffix: jpg,png
  #  文件导入地址
  fileInputPath: ${windowsfile}/file/
#sql备份地址
databaseSavePath: ${windowsfile}/sql/
#mysql mysqldump地址
blackup:
  mysqldump: C://Program Files/MySQL/MySQL Server 5.5/bin
  databaseName: hbcrm
  databaseHost: localhost

#  filepath
windowsfile: D:\hbcrmUpload
#login
loginHtml: hblogin